export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const ADD_TO_CART_RESET = 'ADD_TO_CART_RESET';

export const GET_CART_DETAILS_REQUEST = 'GET_CART_DETAILS_REQUEST';
export const GET_CART_DETAILS_SUCCESS = 'GET_CART_DETAILS_SUCCESS';
export const GET_CART_DETAILS_FAIL = 'GET_CART_DETAILS_FAIL';
